language: java
install: true
jdk: oraclejdk8

env:
  matrix:
  - TERM=dumb

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./gradlew clean build jacocoTestReport jacocoRootMergeReport -S

after_success:
  - ./gradlew coveralls
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    ./gradlew :dolphin-platform-documentation:asciidoctor;
    cd documentation/dolphin-platform-documentation/build/asciidoc/html5/;
    git init;
    git config user.name "${GH_USER_NAME}";
    git config user.email "{GH_USER_EMAIL}";
    git add . ; git commit -m "Deploy to GitHub Pages";
    git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1;
    fi
